# models:
#  name of the model:
#    filename: file localization
#    language: language of the model (for tokenization)
port: 9009
threads: 2
debug: 1
models:
  language_identification: 
    filename: resources/lid.176.ftz
    language: xx
